import_texts_from: excel # TODO: alternatives?
input_file: ./data.xlsx
sheet: paragraphs
id_column: A
text_column: B
output_dir: ./website/processed-texts
include_all_sentences: 'True'
clozes_per_text: 5
alternative_suggestions_per_cloze: 4
paragraph_session_length: 2
sentence_session_length: 10
simple_language_starting_id: 1216
