version: '3.7'
services:
  couchdb:
    image: couchdb:2.3.1
    ports:
      - 5984:5984
    volumes:
      - ./backend/couchdb/data:/opt/couchdb/data
  backend:
    image: node:12.16
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ../node_modules
        target: /app/node_modules
    command: ['node', '/app/backend/server.js']
    depends_on:
      - couchdb
  frontend:
    image: node:12.16-alpine3.9
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - type: bind
        source: .
        target: /app
      - type: bind
        source: ../node_modules
        target: /app/node_modules
      - type: bind
        source: ../package.json
        target: /app/package.json
    command: ['npm', 'start']
    depends_on:
      - backend
  nginx:
    image: nginx:1.17.8
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
