version: '3.7'
services:
  couchdb:
    container_name: couchdb
    image: couchdb:2.3.1
    restart: always
    ports:
      - 127.0.0.1:5984:5984
    volumes:
      - ./couchdb/data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "8080"
    depends_on:
      - couchdb
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:1.17.8-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./production/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
  certbot:
    image: certbot/certbot:v1.3.0
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'while true; do certbot renew; sleep 43200; done'"
