version: '3.7'
services:
  couchdb:
    container_name: couchdb
    image: couchdb:2.3.1
    ports:
      - 5984:5984
    volumes:
      - ./couchdb/data:/opt/couchdb/data
  backend:
    container_name: backend
    image: node:12.16
    ports:
      - 8080:8080
    volumes:
      - ./backend:/app/backend
    working_dir: /app
    command: ['node', 'backend/server.js']
    depends_on:
      - couchdb
  frontend:
    container_name: frontend
    image: node:12.16-alpine3.9
    ports:
      - 3000:3000
    working_dir: /app
    env_file: .env
    volumes:
      - ./frontend:/app
    command: ['npm', 'start']
    depends_on:
      - backend
  nginx:
    container_name: nginx
    image: nginx:1.17.8
    ports:
      - 8000:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
