version: '3.7'
services:
  couchdb:
    image: couchdb:2.3.1
    ports:
      - 5984:5984
  backend:
    image: node:12.16
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: .
        target: /app
    command: ['node', '/app/server.js']
    depends_on:
      - couchdb
  frontend:
    image: node:12.16-alpine3.9
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: .
        target: /app
    command: ['npm', 'run', '--prefix', '/app', 'start']
    depends_on:
      - backend
  nginx:
    image: nginx:1.17.8
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
