name: Deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Frontend
        uses: elgohr/Publish-Docker-Github-Action@5d8ac99
        with:
          name: 'malfynnction/bachelor-frontend'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: website/frontend
      - name: Publish Backend
        uses: elgohr/Publish-Docker-Github-Action@5d8ac99
        with:
          name: 'malfynnction/bachelor-backend'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: website/backend
      - name: Copy production dir to server
      - name: Deploy
