name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER: text-stat.qu.tu-berlin.de
      USER: adminuser
    steps:
      - uses: actions/checkout@v1
      - name: Publish Frontend
        uses: elgohr/Publish-Docker-Github-Action@5d8ac99
        with:
          name: 'malfynnction/bachelor-frontend'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: website/frontend
          tags: 'latest'
      - name: Publish Backend
        uses: elgohr/Publish-Docker-Github-Action@5d8ac99
        with:
          name: 'malfynnction/bachelor-backend'
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          workdir: website/backend
          tags: 'latest'
      - name: Copy production dir to server
        uses: appleboy/scp-action@edc8ec9
        with:
          host: ${{ env.SERVER }}
          username: ${{ env.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY  }}
          source: website/production/*
          target: production
          strip_components: 2
      - name: Deploy
        uses: fifsky/ssh-action@1f1f1ea
        with:
          command: |
            cd production
            echo "COUCHDB_PASSWORD=${{ secrets.COUCHDB_PASSWORD }}" > .env
            docker-compose pull && docker-compose up -d
            crontab ./cronfile
          host: ${{ env. SERVER }}
          user: ${{ env.USER }}
          key: ${{ secrets.PRIVATE_SSH_KEY }}
